
#Adaptive Performance Tweaks: Spawn
["Minecraft Spawn Config"]
	Enabled = true
	Id = "minecraft"
	#e.g. mobs which will not attack you
	#Range: 1 ~ 64
	MaxPassiveMobsPerPlayer = 8
	#Range: 1 ~ 512
	MaxPassiveMobsPerWorld = 32
	#Range: 1 ~ 1024
	MaxPassiveMobsPerServer = 320
	#List of passive Mobs to optimize in the format ["minecraft:bat", "minecraft:cat", ..]
	PassiveMobsList = ["minecraft:skeleton_horse"]
	#e.g. mobs which will attack under certain conditions ...
	#Range: 1 ~ 64
	MaxNeutralMobsPerPlayer = 8
	#Range: 1 ~ 512
	MaxNeutralMobsPerWorld = 32
	#Range: 1 ~ 1024
	MaxNeutralMobsPerServer = 320
	#List of neutral Mobs to optimize in the format ["minecraft:bee", "minecraft:wolf", ..]
	NeutralMobsList = ["minecraft:zombie_horse"]
	#e.g. mobs which will always attack yon ...
	#Range: 1 ~ 64
	MaxHostileMobsPerPlayer = 8
	#Range: 1 ~ 512
	MaxHostileMobsPerWorld = 32
	#Range: 1 ~ 1024
	MaxHostileMobsPerServer = 320
	#List of hostile Mobs to optimize in the format ["minecraft:blaze", "minecraft:cave_spider", ..]
	HostileMobsList = ["minecraft:zombie_villager"]
	#e.g. mostly fish
	#Range: 1 ~ 64
	MaxWaterPassiveMobsPerPlayer = 8
	#Range: 1 ~ 512
	MaxWaterPassiveMobsPerWorld = 32
	#Range: 1 ~ 1024
	MaxWaterPassiveMobsPerServer = 320
	#List of passive water Mobs to optimize
	WaterPassiveMobsList = ["minecraft:tropical_fish"]
	#e.g. squid, dolphin, ...
	#Range: 1 ~ 64
	MaxWaterNeutralMobsPerPlayer = 6
	#Range: 1 ~ 512
	MaxWaterNeutralMobsPerWorld = 24
	#Range: 1 ~ 1024
	MaxWaterNeutralMobsPerServer = 320
	#List of neutral water Mobs to optimize
	WaterNeutralMobsList = []
	#e.g. drowned, guardian...
	#Range: 1 ~ 64
	MaxWaterHostileMobsPerPlayer = 16
	#Range: 1 ~ 512
	MaxWaterHostileMobsPerWorld = 64
	#Range: 1 ~ 1024
	MaxWaterHostileMobsPerServer = 320
	#List of hostile water Mobs to optimize
	WaterHostileMobsList = []

