#Advanced settings for performance and stability.
performance_tuning = {}

#General settings for the mod.
[general]
	#Enable or disable the mod entirely.
	enabled = true
	#Show a warning when using the mod in singleplayer.
	singleplayer-warning = true
	#Enable automatic update checks.
	automatic-updater = true

#Enable or disable specific acceleration features.
[acceleration_modules]
	#Accelerate block entities (e.g., furnaces, hoppers). Can cause issues.
	block_entity = false
	#Accelerate block breaking.
	block_breaking = true
	#Accelerate potion effect timers.
	potion_effect = true
	#Accelerate fluid flow.
	fluid = true
	#Accelerate item pickup delay.
	item_pickup = true
	#Accelerate eating and drinking animations.
	eating = true
	#Accelerate nether portal teleportation time.
	nether_portal = true
	#Accelerate time to pass the night when sleeping.
	sleeping = true
	time = true

