#Advanced settings for performance and stability.
performance_tuning = {}

#General settings for the mod.
[general]
	#Enable or disable the mod entirely.
	enabled = true
	#Show a warning when using the mod in singleplayer.
	singleplayer-warning = true
	automatic-updater = true

