
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = false

[CraftingMapper]

	[CraftingMapper.MekRotary]
		#Maps Mekanism rotary condensentrator recipes.
		enabled = true

	[CraftingMapper.MekItemStackToPigment]
		#Maps Mekanism item stack to pigment recipes. (Pigment Extracting)
		enabled = true

	[CraftingMapper.MekElectrolysis]
		#Maps Mekanism electrolytic separator recipes.
		enabled = true

	[CraftingMapper.MekPaintingMachine]
		#Maps Mekanism painting machine recipes.
		enabled = true

	[CraftingMapper.MekItemStackGasToItemStack]
		#Maps Mekanism Machine recipes that go from item, gas to item. (Compressing, Purifying, Injecting)
		enabled = true

	[CraftingMapper.MekDissolution]
		#Maps Mekanism dissolution recipes.
		enabled = true

	[CraftingMapper.MekGasToGas]
		#Maps Mekanism activating and centrifuging recipes.
		enabled = true

	[CraftingMapper.MekFluidSlurryToSlurry]
		#Maps Mekanism washing recipes.
		enabled = true

	[CraftingMapper.MekItemStackToItemStack]
		#Maps Mekanism Machine recipes that go from item to item. (Crushing, Enriching, Smelting)
		enabled = true

	[CraftingMapper.MekSawmill]
		#Maps Mekanism sawmill recipes. (Disabled by default, due to causing various EMC values to be removed pertaining to charcoal/wood)
		enabled = false

	[CraftingMapper.MekChemicalInfuser]
		#Maps Mekanism chemical infuser recipes.
		enabled = true

	[CraftingMapper.MekCombiner]
		#Maps Mekanism combiner recipes.
		enabled = true

	[CraftingMapper.MekPressurizedReaction]
		#Maps Mekanism pressurized reaction recipes.
		enabled = false

	[CraftingMapper.MekFluidToFluid]
		#Maps Mekanism evaporating recipes.
		enabled = true

	[CraftingMapper.MekChemicalCrystallizer]
		#Maps Mekanism crystallizing recipes.
		enabled = true

	[CraftingMapper.Smithing]
		#Maps smithing recipes.
		enabled = true

	[CraftingMapper.MekMetallurgicInfuser]
		#Maps Mekanism metallurgic infuser recipes.
		enabled = true

	[CraftingMapper.MekPigmentMixer]
		#Maps Mekanism pigment mixer recipes.
		enabled = true

	[CraftingMapper.MekItemStackToGas]
		#Maps Mekanism item stack to gas recipes. (Gas conversion, Oxidizing)
		enabled = true

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe, SingleItemRecipe, or SmithingRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

	[CraftingMapper.MekItemStackToInfuseType]
		#Maps Mekanism item stack to infuse type conversion recipes.
		enabled = true

	[CraftingMapper.IndustrialForegoingStoneWorksGenerateMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Stone Works Generate Mapper. Required Mods: [industrialforegoing] NOTE: Disabled by default.
		enabled = false

	[CraftingMapper.IndustrialForegoingDissolutionChamberMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Dissolution Chamber Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.IndustrialForegoingCrusherMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Crusher Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.FarmersDelightCuttingBoardMapper]
		#ProjectE-Integration Recipe Mapper for Farmers Delight Cutting Board Mapper. Required Mods: [farmersdelight]
		enabled = true

	[CraftingMapper.FarmersDelightCookingPotMapper]
		#ProjectE-Integration Recipe Mapper for Farmers Delight Cooking Pot Mapper. Required Mods: [farmersdelight]
		enabled = true

	[CraftingMapper.ElementalCraftSpellCraftMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Spell Craft Mapper. Required Mods: [elementalcraft]
		enabled = true

	[CraftingMapper.ElementalCraftSawingMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Sawing Mapper. Required Mods: [elementalcraft]
		enabled = true

	[CraftingMapper.ElementalCraftPureInfusionMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Pure Infusion Mapper. Required Mods: [elementalcraft]
		enabled = true

	[CraftingMapper.ElementalCraftInscriptionMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Inscription Mapper. Required Mods: [elementalcraft]
		enabled = true

	[CraftingMapper.ElementalCraftInfusionMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Infusion Mapper. Required Mods: [elementalcraft]
		enabled = true

	[CraftingMapper.ElementalCraftGrindingMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Grinding Mapper. Required Mods: [elementalcraft]
		enabled = true

	[CraftingMapper.ElementalCraftCrystallizationMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Crystallization Mapper. Required Mods: [elementalcraft] NOTE: Skips all recipes with more than one output chance
		enabled = true

	[CraftingMapper.ElementalCraftBindingMapper]
		#ProjectE-Integration Recipe Mapper for Elemental Craft Binding Mapper. Required Mods: [elementalcraft]
		enabled = true

	[CraftingMapper.CreateSplashingMapper]
		#ProjectE-Integration Recipe Mapper for Create Splashing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateSequencedAssemblyMapper]
		#ProjectE-Integration Recipe Mapper for Create Sequenced Assembly Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateSandpaperPolishingMapper]
		#ProjectE-Integration Recipe Mapper for Create Sandpaper Polishing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreatePressingMapper]
		#ProjectE-Integration Recipe Mapper for Create Pressing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateCUTTINGMapper]
		#ProjectE-Integration Recipe Mapper for Create CUTTINGMapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateMillingMapper]
		#ProjectE-Integration Recipe Mapper for Create Milling Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateMechanicalCraftingMapper]
		#ProjectE-Integration Recipe Mapper for Create Mechanical Crafting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateItemApplicationMapper]
		#ProjectE-Integration Recipe Mapper for Create Item Application Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateHauntingMapper]
		#ProjectE-Integration Recipe Mapper for Create Haunting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateDeployerApplicationMapper]
		#ProjectE-Integration Recipe Mapper for Create Deployer Application Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateCuttingMapper]
		#ProjectE-Integration Recipe Mapper for Create Cutting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateCrushingMapper]
		#ProjectE-Integration Recipe Mapper for Create Crushing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateCompactingMapper]
		#ProjectE-Integration Recipe Mapper for Create Compacting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateBASINMapper]
		#ProjectE-Integration Recipe Mapper for Create BASINMapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.BloodMagicTartaricForgeMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Tartaric Forge Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.BloodMagicBloodAltarMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Blood Altar Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.BloodMagicAlchemyTableMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Alchemy Table Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.BloodMagicAlchemyArrayMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Alchemy Array Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.ArsNouveauImbuementMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Imbuement Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.ArsNouveauGlyphMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Glyph Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.ArsNouveauEnchantingApparatusMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Enchanting Apparatus Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.ArsNouveauCrushMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Crush Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.AppliedEnergisticsInscriberMapper]
		#ProjectE-Integration Recipe Mapper for Applied Energistics Inscriber Mapper. Required Mods: [ae2]
		enabled = true

	[CraftingMapper.ChippedMechanistWorkbenchMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Mechanist Workbench Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ChippedMasonTableMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Mason Table Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ChippedLoomTableMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Loom Table Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ChippedGlassblowerMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Glassblower Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ChippedCarpentersTableMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Carpenters Table Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ChippedBotanistWorkbenchMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Botanist Workbench Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ChippedAlchemyBenchMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Alchemy Bench Mapper. Required Mods: [chipped]
		enabled = true

[enabledMappers]
	#Set EMC=0 for everything in the forge:raw_materials tag
	RawOresBlacklistMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = true
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Add Conversions for all weathered copper variants
	WeatheredCopperMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true
	#Recipe mapper for custom recipes that don't implement IRecipe
	ProjectEIntegrationRecipeMapper = true

