#.
#URL to send data to.
"Metrics Endpoint URL" = ""
#.
#Identifier for this modpack
"Pack ID" = "concatenation"
#.
#Interval between keepalive requests, in minutes.
#Range: > -2147483648
"Update Rate" = 30

